name: dawui_website
description: Website for the dawui package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  dawui:
    path: ../dawui/project

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
